export const GET_QUESTION = 'GET_QUESTION';
export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS';
export const GET_QUESTION_FAILED = 'GET_QUESTION_FAILED';

export const SEND_ANSWER = 'SEND_ANSWER';
export const SEND_ANSWER_SUCCESS = 'SEND_ANSWER_SUCCESS';
export const SEND_ANSWER_FAILED = 'SEND_ANSWER_FAILED';

export const SEND_POINTS = 'SEND_POINTS';
export const SEND_POINTS_SUCCESS = 'SEND_POINTS_SUCCESS';
export const SEND_POINTS_FAILED = 'SEND_POINTS_FAILED';
